import { Multa, InfraccionCatalogo } from './types';

export const CATALOGO_INFRACCIONES: InfraccionCatalogo[] = [
  {
    codigo: 'M-01',
    nombre: 'Conducir con presencia de alcohol en la sangre o bajo efectos de estupefacientes',
    gravedad: 'Muy Grave',
    montoBase: 2150.00,
    puntos: 100,
    retencionLicencia: true,
  },
  {
    codigo: 'M-02',
    nombre: 'Exceder en más de 30 km/h el límite de velocidad máxima establecido',
    gravedad: 'Muy Grave',
    montoBase: 950.00,
    puntos: 50,
    retencionLicencia: false,
  },
  {
    codigo: 'G-10',
    nombre: 'No respetar la luz roja del semáforo o la señal de pare',
    gravedad: 'Grave',
    montoBase: 420.00,
    puntos: 30,
    retencionLicencia: false,
  },
  {
    codigo: 'G-14',
    nombre: 'Estacionar en zonas prohibidas o rígidas señalizadas',
    gravedad: 'Grave',
    montoBase: 310.00,
    puntos: 20,
    retencionLicencia: false,
  },
  {
    codigo: 'G-28',
    nombre: 'Usar teléfono móvil sin manos libres durante la conducción',
    gravedad: 'Grave',
    montoBase: 380.00,
    puntos: 25,
    retencionLicencia: false,
  },
  {
    codigo: 'L-01',
    nombre: 'No portar el cinturón de seguridad los ocupantes del vehículo',
    gravedad: 'Leve',
    montoBase: 180.00,
    puntos: 10,
    retencionLicencia: false,
  },
  {
    codigo: 'L-05',
    nombre: 'Circular sin tener las luces reglamentarias encendidas',
    gravedad: 'Leve',
    montoBase: 150.00,
    puntos: 10,
    retencionLicencia: false,
  }
];

export const MULTAS_INICIALES: Multa[] = [
  {
    id: 'MUL-2026-00891',
    codigoInfraccion: 'M-02',
    placa: 'ABC-123',
    conductor: 'Carlos Eduardo Ramírez Peña',
    dniConductor: '74829103',
    tipoVehiculo: 'Automóvil',
    fecha: '2026-08-25',
    hora: '14:32',
    lugar: 'Av. Javier Prado Este cuadra 28, San Borja',
    descripcion: 'Cinemómetro detectó velocidad de 92 km/h en zona regulada a 60 km/h.',
    gravedad: 'Muy Grave',
    monto: 950.00,
    descuentoProntoPago: 50,
    estado: 'Pendiente',
    agenteId: 'POL-T-4521',
    fechaLimitePago: '2026-09-15'
  },
  {
    id: 'MUL-2026-00885',
    codigoInfraccion: 'G-10',
    placa: 'XYZ-789',
    conductor: 'Mariana Sofia Torres Ruiz',
    dniConductor: '41982054',
    tipoVehiculo: 'Camioneta',
    fecha: '2026-08-18',
    hora: '09:15',
    lugar: 'Intersección Jr. Huancavelica con Tacna, Cercado',
    descripcion: 'Cruce intempestivo de intersección con luz roja del semáforo.',
    gravedad: 'Grave',
    monto: 420.00,
    descuentoProntoPago: 50,
    estado: 'Pagada',
    agenteId: 'POL-T-3108',
    fechaLimitePago: '2026-09-08',
    fechaPago: '2026-08-22',
    metodoPago: 'Tarjeta de Débito / Pago Online'
  },
  {
    id: 'MUL-2026-00874',
    codigoInfraccion: 'G-14',
    placa: 'ABC-123',
    conductor: 'Carlos Eduardo Ramírez Peña',
    dniConductor: '74829103',
    tipoVehiculo: 'Automóvil',
    fecha: '2026-07-10',
    hora: '11:05',
    lugar: 'Calle Los Pinos 140, Miraflores',
    descripcion: 'Vehículo estacionado sobre rampa de acceso para personas con discapacidad.',
    gravedad: 'Grave',
    monto: 310.00,
    descuentoProntoPago: 0,
    estado: 'Vencida',
    agenteId: 'POL-T-1922',
    fechaLimitePago: '2026-07-31'
  },
  {
    id: 'MUL-2026-00862',
    codigoInfraccion: 'G-28',
    placa: 'MOT-456',
    conductor: 'Jorge Alberto Meneses Castro',
    dniConductor: '48201938',
    tipoVehiculo: 'Motocicleta',
    fecha: '2026-08-29',
    hora: '17:40',
    lugar: 'Vía Expresa Paseo de la República, altura Canaval y Moreyra',
    descripcion: 'Manipulación de smartphone mientras conducía moto lineal en carril central.',
    gravedad: 'Grave',
    monto: 380.00,
    descuentoProntoPago: 50,
    estado: 'En Apelación',
    agenteId: 'POL-T-8820',
    fechaLimitePago: '2026-09-20'
  },
  {
    id: 'MUL-2026-00850',
    codigoInfraccion: 'L-01',
    placa: 'BUS-990',
    conductor: 'Roberto Dávila Flores',
    dniConductor: '10938472',
    tipoVehiculo: 'Bus',
    fecha: '2026-08-30',
    hora: '08:20',
    lugar: 'Panamericana Norte Km 24',
    descripcion: 'Conductor y copiloto sin cinturón de seguridad en ruta interurbana.',
    gravedad: 'Leve',
    monto: 180.00,
    descuentoProntoPago: 50,
    estado: 'Pendiente',
    agenteId: 'POL-T-5512',
    fechaLimitePago: '2026-09-25'
  }
];
